name: Reproduce Cloudsmith Format Bug

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Copy env
        run: cp .env.production .env.production.local

      - name: Build
        run: npm run build

      - name: Archive build output
        run: tar -czvf dummy.tar.gz dummy.txt

      - name: Push to Cloudsmith
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "raw"
          owner: "rini-jain-rnye"     # Cloudsmith account/namespace
          repo: "new_repo1"           # Cloudsmith repository slug
          file: "dummy.tar.gz"        # File to upload
          name: "dummy.tar.gz"        # Package name in Cloudsmith
          version: 3.7.${{ github.run_number }}
