name: Reproduce Cloudsmith Format Bug

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-node@v2
          with:
          node-version: "20"

        - run: npm ci --legacy-peer-deps
        - run: cp .env.production .env.production.local
        - run: npm run build
        - run: tar -czvf resurfaceio-ui.tar.gz out
        - name: Push
          id: push
          uses: cloudsmith-io/action@master
          with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "raw"
          owner: "rini-jain-rnye" # Your Cloudsmith account name or org name (namespace)
          repo: "new_repo1" # Your Cloudsmith Repository name (slug)
          file: "dummy.tar.gz" # Name of file
          name: "dummy.tar.gz" # Name for Raw package
          version: 3.7.${{github.run_number}}
              
